tpwd/ke_search

Classes/Backend/Filterlist.php
Classes/Backend/Flexform.php
Classes/Controller/AbstractBackendModuleController.php
Classes/Indexer/Types/Page.php

This fixes the following issues:
An error occurred trying to process items for field "Tags for faceted search" (PHP Warning: Undefined array key "tx_kesearch." in /var/www/html/public/typo3conf/ext/ke_search/Classes/Backend/Filterlist.php line 85).
An error occurred trying to process items for field "Sorting for searchresults" (PHP Warning: Undefined array key "relevanceNotAllowed" in /var/www/html/public/typo3conf/ext/ke_search/Classes/Backend/Flexform.php line 48).
PHP Warning: Undefined array key 0 in /var/www/html/public/typo3conf/ext/ke_search/Classes/Indexer/Types/Page.php line 415

[BUGFIX] Fix PHP8 issues in backend

---

.gitignore
composer.json

The dependencies (in the vendor folder) and the public folder (named then "web")
are moved into a .Build folder. This way it can be easily ignored and deleted
when necessary.
This is a common pattern in TYPO3 extensions, like TYPO3 console:
https://github.com/TYPO3-Console/TYPO3-Console/blob/latest/composer.json

[TASK] Use .Build folder for dependencies

---

Configuration/Icons.php
ext_tables.php

This way the loading speed is improved for every request in TYPO3 v11+.
See also: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.4/Feature-94692-RegisteringIconsViaServiceContainer.html
Additionally, the SVG provider is used for icon registering in TYPO3 v10 instead
of the bitmap provider.

[TASK] Register icons via service container

---

Classes/Indexer/Types/News.php
Classes/Indexer/Types/Page.php

PHP Runtime Deprecation Notice: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/html/public/typo3conf/ext/ke_search/Classes/Indexer/IndexerRunner.php line 1169
The upper message is caused by the abstract of a page to be null. The abstract is therefore casted to a string,
as storeInIndex() is expecting a string according to the annotation.
PHP Runtime Deprecation Notice: http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in /var/www/html/public/typo3conf/ext/ke_search/Classes/Indexer/Types/News.php line 255

[TASK] Avoid PHP 8.1 deprecations when indexing

---

Classes/Widgets/StatusWidget.php

The hours are not assigned correctly to the view. Also, in the hours calculation the number was rounded, instead it must be floor'ed.
Additionally, two deprecations in PHP 8.1 were fixed:
PHP Runtime Deprecation Notice: Implicit conversion from float 2.0166666666666666 to int loses precision in /var/www/html/public/typo3conf/ext/ke_search/Classes/Widgets/StatusWidget.php line 65
PHP Runtime Deprecation Notice: Implicit conversion from float 0.13333333333333333 to int loses precision in /var/www/html/public/typo3conf/ext/ke_search/Classes/Widgets/StatusWidget.php line 80
See also: https://3v4l.org/AKBBH

[BUGFIX] Display hours in status widget correctly

---

Configuration/Backend/DashboardPresets.php
Resources/Private/Language/de.locallang_dashboard.xlf
Resources/Private/Language/locallang_dashboard.xlf

When creating a new dashboard for search you mostly want to add all widgets to that
dashboard. A dashboard preset simplifies that task with only one click.

[FEATURE] Add dashboard preset

---

.gitattributes

"export-ignore" means basically that the are ignored when installing
an extension version via composer. These files aren't necessary on
production systems.
See: https://git-scm.com/docs/gitattributes#_creating_an_archive

[TASK] Add .gitattributes files

---

Classes/Indexer/Types/Page.php
Configuration/TCA/tx_kesearch_indexerconfig.php
Resources/Private/Language/de.locallang_db.xlf
Resources/Private/Language/locallang_db.xlf
Resources/Private/Language/nl.locallang_db.xlf

Doktypes 2 and 5 are not available anymore in recent LTS versions, so they
should be dropped.
See: https://github.com/TYPO3/typo3/blob/10.4/typo3/sysext/core/Classes/Domain/Repository/PageRepository.php#L106

[TASK] Remove outdated doktypes

---

Documentation/Configuration/Sorting.rst
Documentation/Multilingual/Index.rst

The "alternative page language" record is gone in TYPO3 v10. The note for
TYPO3 v9 is dropped.
Additionally, a typo on "Sorting" page was fixed.

[DOCS] Revise "Translating filter" section

---

Classes/Backend/Flexform.php

Defining an additional field without adding according TCA throws the following errors
for PHP8 when editing the plugin for searchbox and filters (pi1):
An error occurred trying to process items for field "Sorting for searchresults" (PHP Warning: Undefined array key "my_additional_field" in /var/www/html/public/typo3conf/ext/ke_search/Classes/Backend/Flexform.php line 57).
An error occurred trying to process items for field "Sorting for searchresults if no searchword/filter is given" (PHP Warning: Undefined array key "my_additional_field" in /var/www/html/public/typo3conf/ext/ke_search/Classes/Backend/Flexform.php line 57).
An error occurred trying to process items for field "Fields the website user should be able to order by" (PHP Warning: Undefined array key "my_additional_field" in …

[BUGFIX] Add fallback when label in TCA is not defined

---

Classes/Lib/Pluginbase.php

The patch fixes an exception in frontend when "Availability check for filter options" in plugin
flexform is set to "no check":
PHP Warning: Undefined array key "results" in /var/www/html/public/typo3conf/ext/ke_search/Classes/Lib/Pluginbase.php line 484

[BUGFIX] Avoid undefined array key when filter options availability is not checked

---

Classes/Indexer/Filetypes/Doc.php
Classes/Indexer/Filetypes/Pdf.php
Classes/Indexer/Filetypes/Ppt.php
Classes/Lib/SearchHelper.php
Documentation/Configuration/Index.rst
Documentation/Configuration/Notes.rst
Documentation/Indexing/IndexerTypes/Files.rst
Documentation/Logging/Index.rst

The configuration is not available anymore in the extension manager in recent
TYPO3 versions.

[TASK] Use "extension configuration" over "extension manager configuration"

---

ext_localconf.php

The new syntax is slightly different over the previous one: If loglevel is an empty
string, this is now okay. But as the loglevel is a select box in the
extension configuration without an empty value, this is neglectable.
Additionally, use ::class instead of string for FileWriter class.

[TASK] Simplify determining of log level in ext_localconf.php

---

Resources/Private/Layouts/Backend/Alert.html

This ensures that the stylesheet can be loaded correctly when using
typo3/cms-composer-installers v4.
See: https://b13.com/core-insights/typo3-and-composer-weve-come-a-long-way

[BUGFIX] Avoid typo3conf path when including backend CSS file

---

composer.json

Compat with older PHP versions than 7.4 was restored once before (https://github.com/tpwd/ke_search/pull/5) but implicitly dropped again in the meantime (https://github.com/tpwd/ke_search/commit/3b3360ea1d52cb0f827dffd0aaf67527b7bbd77c)
Thus the minimum required PHP version must be stated explicitly.

Add PHP version constraint

---

ext_emconf.php

Only properties are provided now which are described in
https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ExtensionArchitecture/DeclarationFile/Index.html
Additionally, a constraint for the PHP version was added to meet the constraint in composer.json
and short array syntax is used.

[TASK] Clean up ext_emconf.php

---

Classes/Lib/Pluginbase.php

undefined array key includeFilters in Pluginbase.php

---

Classes/Lib/Filters.php

This allows the starting points to be accessed via the filter hooks
---
We have a custom filter which needs to know about the starting points (as it needs to get data from the indexers). Currently using the `pid` of the filter but doesn't pick up any additional places uses

Add startingPoints public method to Filter class

---

Classes/Indexer/Types/Page.php

I added $field to the modifyContentFromContentElement hook, because the hook is executed for each entry from tx_kesearch_indexerconfig.content_fields.
This causes problems when modifying/extending the $bodytext because the modification will be done as many times as there are additional fields in the content_fields column of the tx_kesearch_indexerconfig table.
Passing the $field variable to the hook enables us to only executing the hook for a given field.
The change is backwards compatible since php just ignores arguments which are not present in the method signature.

[BUGFIX] Pass $field to modifyContentFromContentElement hook

---

Classes/Indexer/IndexerBase.php

The class IndexerBase is missing type-hint on its constructor argument. This prevents us from using dependency injection in the consuming custom indexers.

[TASK] Properly type-hint IndexerBase constructor

---

Classes/Indexer/Types/Page.php

TYPO3 11.5.36
ke_search 5.2.1
PHP 8.2.15
Manually starting the Indexer failed in the BE.
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1476107295: PHP Warning: Undefined array key "alternative" in /var/www/typo3/public/typo3conf/ext/ke_search/Classes/Indexer/Types/Page.php line 1189 | TYPO3\CMS\Core\Error\Exception thrown in file /var/www/typo3/public/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 137. Requested URL: https://my.domain.tld/typo3/module/web/KeSearchBackendModule?token=--AnonymizedToken--&id=217&do=startindexer `
or
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1476107295: PHP Warning: Undefined array key "description" in /var/www/typo3/public/typo3conf/ext/ke_search/Classes/Indexer/Types/Page.php line 1184 | TYPO3\CMS\Core\Error\Exception …

PHP Warning: Undefined array key "alternative" (and "description")

---

Configuration/TCA/tx_kesearch_filteroptions.php
Configuration/TCA/tx_kesearch_filters.php
Configuration/TCA/tx_kesearch_index.php
Configuration/TCA/tx_kesearch_indexerconfig.php

Without this settings you cannot see nor add new configs via list module. Required for TYPO3 v12.

TYPO3 v12: Add "ignorePageTypeRestriction" to TCA configs

---

ChangeLog
Classes/Domain/Repository/IndexRepository.php
Classes/Indexer/IndexerBase.php
Classes/Indexer/Types/File.php
Classes/Indexer/Types/News.php
Classes/Indexer/Types/Page.php
Classes/Indexer/Types/TtAddress.php
Classes/Indexer/Types/TtContent.php
Classes/Indexer/Types/TtNews.php

Some records will be skipped during
full indexing, e.g. page records that have the
"no_index" flag or news records without
required categories. Incremental indexing
currently only removes "deleted" and
"hidden" records but should also remove
records that would be skipped for other
reasons in normal indexing.
During incremental tt_content record which
should not be indexed (e.g. parent page has
"no_search" flag is set) will
now be removed from the index.
During incremental indexing files which
should not be indexed (e.g.
"tx_kesearch_no_search" flag is set) will
now be removed from the index.
Additionally instantiating indexerStatusService
and indexRepository has now been moved to the
IndexerBase class, along with the functions
removeRecordFromIndex, removeFileFromIndex and …

Remove records in incremental mode

---

Classes/Indexer/Types/Page.php

If Page Indexer has configured non-standard doktypes, respect them for auto-tagging. 
Fixes #233

[BUGFIX] Respect configured Doktypes while Auto-Tagging

---

.github/workflows/ci.yml

Update actions/checkout and actions/cache to the recent version 4.
Additionally, replace a deprecation:
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files.

[TASK] Update workflow actions

---

Classes/Indexer/Types/Page.php

This PR moves the check for whether a content element's header field should be indexed to a separate method.
I need this change because I'm overriding/extending the page indexer and want to extend this logic. 
We use the header field for some elements as a backend-only field, so it needs to be excluded from the index.
I noticed a TODO comment in the tt_content indexer regarding making this check customizable via a hook. Are there any updates or plans for when this might be implemented?
For now, I would appreciate it if this PR could be merged.
Thank you for your time,
Joost

[TASK] Move check if header field should be indexed in separate method

---

Classes/Indexer/Types/File.php
Configuration/TCA/tx_kesearch_indexerconfig.php
Resources/Private/Language/locallang_db.xlf
ext_tables.sql

As mentioned in #294, this is something we added in a specific project but thought it would be beneficial to have in the core package.
Currently, selecting a FAL storage makes the field appear - this is a small hack so that [this conditional triggers](https://github.com/tpwd/ke_search/blob/master/Classes/Indexer/Types/File.php#L445).
I'm not expecting this hack to stay, but wanted to get the rest of the code in there to start review & conversation.
I was toying with the idea of either adding an extra item to the `fal_storage` field (e.g  "File Collections"  with a value of 9999) or adding a new field of `file_type` or similar which has  "Directories" and "File Collections" as an option, as I can't imagine people would want to mix and match (and, in fact, would cause conflicting and …

Allow File Collections to be indexed
